/** Sound events available to gameplay or exact-variant preview on the listening sheet. */
export const SOUND_EVENT_IDS = [
  'player_hurt_light',
  'player_nope',
  'player_hurt_heavy',
  'player_strain',
  'player_landing_hard',
  'footstep_grass',
  'footstep_mud',
  'footstep_sand',
  'footstep_stone',
  'footstep_wood',
  'footstep_leaves',
  'foliage_rustle',
  'foliage_rustle_fast',
  'shambler_step_grass',
  'shambler_step_mud',
  'shambler_step_sand',
  'shambler_step_stone',
  'shambler_step_wood',
  'shambler_step_leaves',
  'melee_swing',
  'melee_hit',
  'melee_hit_fist',
  'gunshot',
  'gunshot_pbs1_reference',
  'shotgun_blast',
  'shotgun_rack_back',
  'shotgun_rack_forward',
  'shotgun_insert',
  'shotgun_hull_drop',
  'item_drop_wood',
  'pouch_take',
  'shambler_idle',
  'shambler_alert',
  'shambler_attack',
  'shambler_hurt',
  'runner_idle',
  'runner_alert',
  'runner_attack',
  'runner_hurt',
  'crawler_idle',
  'crawler_alert',
  'crawler_attack',
  'crawler_hurt',
  'door_open',
  'door_roller_open',
  'door_close',
  'door_blocked_close',
  'lock_pry',
] as const;

export type SoundEventId = (typeof SOUND_EVENT_IDS)[number];
